sudo: false
language: bash
os:
  - linux

script:
  - set -e
  - ARDUINOVER=arduino-1.6.8
  - THISSKETCH=libraries/ESPVFATFS
  - LIBREPOS=(
    )
  - ( cd "$HOME" &&
      wget -q "http://downloads.arduino.cc/${ARDUINOVER}-linux64.tar.xz" &&
      tar xf ${ARDUINOVER}-linux64.tar.xz ) &
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile
      --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16 &
  - export DISPLAY=:1.0
  - ARDUINOIDE="$HOME/$ARDUINOVER"
  - ARDUINOSDK="$ARDUINOIDE"/hardware/esp8266com
  - mkdir -p "$ARDUINOSDK" && (
      cd "$ARDUINOSDK" &&
      git clone -q https://github.com/Adam5Wu/Arduino.git esp8266 ) &
  - wait && export PATH="$ARDUINOIDE:$PATH"
  - ( cd "$ARDUINOSDK"/esp8266/tools && python get.py ) &
  - export SKETCHBOOK=`arduino --get-pref sketchbook.path`
  - SKETCHLIB="$SKETCHBOOK"/libraries
  - mkdir -p "$SKETCHLIB"
  - for LIBREPO in "${LIBREPOS[@]}" ; do
      LIBNAME=`basename "$LIBREPO"` ;
      echo "- Retriving library '$LIBNAME'..." ;
      git clone -q "$LIBREPO" "$SKETCHLIB/$LIBNAME" &
    done
  - ln -s "$TRAVIS_BUILD_DIR" "$SKETCHBOOK/$THISSKETCH"
  - source "$TRAVIS_BUILD_DIR"/travis/common.sh
  - wait && build_sketches arduino "$SKETCHBOOK/$THISSKETCH" esp8266
      generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=2M

notifications:
  email:
    on_success: change
    on_failure: change
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
